version: '3.7'

services:
  somfy2mqtt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: somfy2mqtt
    image: somfy2mqtt:latest
    restart: always
    tty: true
    privileged: true
    environment:
      - TZ=Europe/Amsterdam
      - PIGPIO_ADDR=
      - PIGPIO_PORT=8888
      - PIGPIOD_ARGS=-e -m -a
    networks:
      - somfy
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/mem
      - /dev/vcio
      - /dev/gpiomem
    volumes:
      - /sys:/sys
      - /srv/docker/data/somfy2mqtt/log:/opt/somfy/log
      - /srv/docker/data/somfy2mqtt/config:/opt/somfy/config
    ports:
     - 8880:80
     - 8443:443
networks:
  somfy:
    driver: overlay
    ipam:
      config:
        - subnet: 172.31.7.0/24